services:
  nginx:
    container_name: inception_nginx
    image: inception/nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - inception_app_data:/app
    networks:
      - inception_net
    restart: always

  wordpress:
    container_name: inception_wordpress
    image: inception/wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - inception_app_data:/app
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

  mariadb:
    container_name: inception_mariadb
    image: inception/mariadb
    build: requirements/mariadb
    volumes:
      - inception_db_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

volumes:

  inception_app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/Users/victorburton/inception/data/wordpress'

  inception_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/Users/victorburton/inception/data/mariadb'

networks:
  inception_net: